# Generated by Django 5.2.12 on 2026-04-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmodel",
            name="is_seen",
        ),
    ]
