# Generated by Django 5.2.12 on 2026-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_remove_contactmodel_is_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="contactmodel",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
