# Generated by Django 5.2.12 on 2026-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_newsletter_contactmodel_is_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
