# Generated by Django 5.2.12 on 2026-04-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_newsletter_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='NewsLetterModel',
        ),
    ]
