# Generated by Django 5.2.12 on 2026-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female'), (3, 'not to mention')], null=True),
        ),
    ]
