# Generated by Django 5.2.12 on 2026-03-16 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="description",
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/default.jpg", upload_to="profile/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
