# Generated by Django 5.2.12 on 2026-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_wishlistproductmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="avg_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
