# Generated by Django 5.2.12 on 2026-04-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_add_gin_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="product_title_gin_idx",
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("attribute", "product")},
        ),
    ]
