# Generated by Django 5.2.12 on 2026-03-24 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_ordermodel_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.couponmodel",
            ),
        ),
    ]
