# Generated by Django 5.2.12 on 2026-03-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordermodel_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
    ]
